# Generated by Django 4.2.5 on 2023-09-26 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('firstname', models.CharField(max_length=255, unique=True)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('deleted', models.IntegerField()),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(db_column='dateTime')),
                ('duration', models.DecimalField(decimal_places=0, max_digits=10)),
                ('deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='Meetingroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('maxcapacity', models.IntegerField(db_column='maxCapacity')),
                ('deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'meetingroom',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='Whiteboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'whiteboard',
            },
        ),
        migrations.CreateModel(
            name='Usersubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirationdate', models.DateTimeField(db_column='expirationDate')),
                ('deleted', models.IntegerField()),
                ('subscriptionid', models.ForeignKey(db_column='subscriptionId', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.subscription')),
                ('userid', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usersubscription',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('meetingid', models.ForeignKey(db_column='meetingId', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.meeting')),
                ('userid', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participant',
            },
        ),
        migrations.CreateModel(
            name='Commentwhiteboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(db_column='dateTime')),
                ('author', models.CharField(max_length=255)),
                ('deleted', models.IntegerField()),
                ('whiteboardid', models.ForeignKey(db_column='whiteboardId', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.whiteboard')),
            ],
            options={
                'db_table': 'commentwhiteboard',
            },
        ),
        migrations.CreateModel(
            name='Commentmeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(db_column='dateTime')),
                ('author', models.CharField(max_length=255)),
                ('deleted', models.IntegerField()),
                ('meetingid', models.ForeignKey(db_column='meetingId', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.meeting')),
            ],
            options={
                'db_table': 'commentmeeting',
            },
        ),
    ]
