# Generated by Django 4.2.5 on 2023-10-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_meetingroom_meetingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='roomname',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
