# Generated by Django 4.2.5 on 2023-10-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_meeting_roomname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='roomname',
            field=models.BigIntegerField(default=0, max_length=30),
        ),
    ]
