# Generated by Django 4.2.5 on 2023-10-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_meeting_roomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiteboard',
            name='whitename',
            field=models.BigIntegerField(default=0),
        ),
    ]
